# Naive Bayes Classification

## Objective

This notebook demonstrates the use of Naive Bayes algorithms for two classification problems:

1. Titanic survival prediction using Gaussian Naive Bayes.
2. Email spam detection using Multinomial Naive Bayes.

## 1. Titanic Survival Prediction

The objective is to predict whether a passenger survived the Titanic disaster using Gaussian Naive Bayes.

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [7]:
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [8]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [9]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [10]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True

In [11]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='str')

In [12]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [13]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500   False
1       1  38.0  71.2833    True
2       3  26.0   7.9250    True
3       1  35.0  53.1000    True
4       3  35.0   8.0500   False

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    inputs,
    target,
    test_size=0.3,
    random_state=42,
    stratify=target
)

In [15]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 76.12%

In [16]:
model.fit(X_train,y_train)

GaussianNB()

In [17]:
model.score(X_test,y_test)

0.7611940298507462

In [18]:
X_test[0:10]

     Pclass        Age     Fare  female
625       1  61.000000  32.3208   False
566       3  19.000000   7.8958   False
459       3  29.699118   7.7500   False
804       3  27.000000   6.9750   False
338       3  45.000000   8.0500   False
745       1  70.000000  71.0000   False
277       2  29.699118   0.0000   False
473       2  23.000000  13.7917    True
157       3  30.000000   8.0500   False
427       2  19.000000  26.0000    True

In [19]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

## 2. Email Spam Detection

The objective is to classify text messages as spam or not spam using Multinomial Naive Bayes.

CountVectorizer is used to transform text messages into numerical features that can be processed by the classifier.

In [20]:
dff = pd.read_csv("spam.csv")
dff.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [21]:
dff['spam']=dff['Category'].apply(lambda x: 1 if x=='spam' else 0)
dff.head()

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dff.Message,dff.spam)

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
# Transformer les messages en données numériques
v = CountVectorizer()

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

X_train_count = v.fit_transform(X_train)
X_test_count = v.transform(X_test)

# Créer et entraîner le modèle
spam_model = MultinomialNB()
spam_model.fit(X_train_count, y_train)

# Évaluer le modèle
accuracy = spam_model.score(X_test_count, y_test)

print(f"Accuracy: {accuracy:.2%}")

Accuracy: 98.99%

In [39]:
emails = [
    "Hey mohan, can we get together to watch football game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!"
]

emails_count = v.transform(emails)

predictions = spam_model.predict(emails_count)

for email, prediction in zip(emails, predictions):
    label = "Spam" if prediction == 1 else "Not Spam"
    print(f"{label}: {email}")

Not Spam: Hey mohan, can we get together to watch football game tomorrow?
Spam: Upto 20% discount on parking, exclusive offer just for you. Don't miss this reward!

In [40]:
X_test_count = v.transform(X_test)
spam_model.score(X_test_count, y_test)

0.9899497487437185

## Conclusion

This notebook demonstrated two applications of Naive Bayes classification.

Gaussian Naive Bayes was used to predict Titanic passenger survival, while Multinomial Naive Bayes combined with CountVectorizer was used for email spam detection.

These examples illustrate how different Naive Bayes variants can be applied to numerical and text classification problems.