# Decision Tree Classification

## Objective
This notebook demonstrates how Decision Tree classifiers can be used for binary classification problems.

Two examples are studied:
1. Salary prediction based on company, job and degree.
2. Passenger survival prediction using the Titanic dataset.

## 1. Salary Classification

The objective is to predict whether a person's salary is greater than $100,000 based on categorical features such as company, job and degree.

In [23]:
import pandas as pd

In [24]:
df = pd.read_csv("salaries.csv")
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [25]:
inputs=df.drop(["salary_more_then_100k"],axis='columns')
target=df["salary_more_then_100k"]

In [26]:
inputs
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

### Encoding Categorical Variables

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
company_encoder = LabelEncoder()
job_encoder = LabelEncoder()
degree_encoder = LabelEncoder()

In [29]:
inputs['company_n'] = company_encoder.fit_transform(inputs['company'])
inputs['job_n'] = job_encoder.fit_transform(inputs['job'])
inputs['degree_n'] = degree_encoder.fit_transform(inputs['degree'])

In [30]:
inputs=inputs.drop(['company','job','degree'],axis='columns')

In [31]:
inputs

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

### Training the Decision Tree

In [ ]:
model = tree.DecisionTreeClassifier()

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(
    inputs,
    target,
    test_size=0.2,
    random_state=42
)

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2%}")

Accuracy: 75.00%

## 2. Titanic Survival Classification

In this section, a Decision Tree classifier is used to predict whether a passenger survived the Titanic disaster.

In [33]:
titanic=pd.read_csv('titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [34]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [35]:
target=titanic.Survived

In [36]:
titanic=titanic.drop(['PassengerId','Name','Cabin','Ticket','Parch','SibSp','Survived','Embarked'],axis='columns')

In [37]:
titanic.head()

   Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [38]:
titanic.Sex = titanic.Sex.map({'male': 1, 'female': 2})

In [39]:
titanic.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

target.head()

In [32]:
titanic.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [34]:
mean_age = titanic.Age.mean()
titanic.Age = titanic.Age.fillna(mean_age)

In [35]:
titanic.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [36]:
titanic

     Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    2  38.000000  71.2833
2         3    2  26.000000   7.9250
3         1    2  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    2  19.000000  30.0000
888       3    2  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
X_train,X_test,y_train,y_test=train_test_split(titanic,target,test_size=0.2)

In [62]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [63]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [64]:
accuracy = model.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2%}")

0.7430167597765364

In [65]:
titanic.head()

   Pclass  Sex   Age     Fare
0       3    1  22.0   7.2500
1       1    2  38.0  71.2833
2       3    2  26.0   7.9250
3       1    2  35.0  53.1000
4       3    1  35.0   8.0500

In [66]:
model.predict([[1,2,27,71.2500]])

/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

## Conclusion

This notebook demonstrates how Decision Tree classifiers can handle different types of classification problems.

Categorical variables were encoded before training, missing values were handled in the Titanic dataset, and the models were evaluated using a train-test split.